name: 'List Pull Requests'
description: 'list and put output pull requests'
branding:
  icon: 'bell'  
  color: 'yellow'
inputs:
  token:
    description: 'github token'
    required: true
    default: ''
  label:
    description: 'Label to filter pull requests'
    required: true
    default: ''
outputs:
  result:
    description: 'pull request string'
runs:
  using: 'node16'
  main: 'index.js'
