name: 'List Pull Requests'
description: 'list and put output pull requests'
branding:
  icon: 'bell'  
  color: 'yellow'
inputs:
  token:
    description: 'github token'
    required: true
    default: ''
  originBranch:
    description: 'The branch to reset from'
    required: true
  targetBranch:
    description: 'The branch to merge into'
    required: true
  label:
    description: 'Label to filter pull requests'
    required: true
outputs:
  result:
    description: 'pull request string'
runs:
  using: 'node16'
  main: 'index.js'
