name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run my action
        uses: ./
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: '["bug"]'